//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEscolar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.Alumno_materia = new HashSet<Alumno_materia>();
            this.Horarios = new HashSet<Horarios>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<int> id_maestro { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<int> capacidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno_materia> Alumno_materia { get; set; }
        public virtual Maestros Maestros { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Periodos Periodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
    }
}
